### ISSUE TITLE
send picture to cv

### ISSUE THREAD

**Issue by demainic** [pm4-graders/3ES#17]

**Comment by joschi27** [comment]
You will have to create an instance of my opencv class and just interact with that. See [DigitRecognizer.py](https://github.com/pm4-graders/3ES/blob/9612d7631d205a813ece1bcc74f24ee177230761/cv/DigitRecognizer.py)

It will give back a json or py dict with 1. A bool if digits have been recognized with proper accuracy and 2. An array with the digits.

**Comment by Re4LyZed** [comment]
close issue because the feature is now implemented
