### ISSUE TITLE
API result generic entries name

### ISSUE THREAD

**Issue by Fab1oNumber1** [pm4-graders/3ES#48]

**Comment by Fab1oNumber1** [comment]
generic name for results in JSON-Response. Example json:

{
    "success": true,
    "entries: [...]
}

![Image](https://user-images.githubusercontent.com/13621417/233381323-018de4ad-cdd5-413c-92cc-c7d4d18670c0.png)

**Comment by Re4LyZed** [comment]
diclined as discussed today
