### ISSUE TITLE
move cv part into backend folder structure

### ISSUE THREAD

**Issue by joschi27** [pm4-graders/3ES#74]
Makes everything easier

**Comment by LordBrud** [comment]
see also: #65

**Comment by joschi27** [comment]
-> @gerbero5 @demainic chönd ihr echt no eu mit de modul usenandsetze und luege das da ganze klappt? ha z.b. mal problem glöst indem i bim digitrecognizer ../ an syspath aghengt ha und denn über cv.MODULNAME gah go t dependencies lade. 

**I bruch eifach unbedingt das wenn /backend/app/cv/app.py usgführt wird das es denn au no tuet.**
